# Generated by Django 4.0.4 on 2022-07-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='topic_name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
