# Generated by Django 4.0.4 on 2022-07-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_entry_topic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='topic_name',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
