# Generated by Django 4.0.4 on 2022-10-20 11:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_remove_entry_topic_name_entry_entry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
